Mark waSCC and WASI Kubelets as NoSchedule
deislabs/krustlet pull request #418
Opened 2020-10-01 14:20 UTC by kflansburg

I believe this is the correct taint, as `NoExecute` applies to Pods that are already running. Probably doesn't hurt to keep `NoExecute` here. Sadly this does  not resolve the `kube-proxy` issue as they seem to apply a wildcard `NoSchedule` toleration.

2020-10-01 18:57 UTC, thomastaylor312 requested changes
I think this is the right thing to do. Can you also update all of the docs and demo manifests to reflect this new change?

2020-10-01 18:59 UTC, thomastaylor312 commented
Oh I think you’ll need to update the e2e tests as well. 

Marking this as breaking so we remember to put something in the release notes

2020-10-02 16:42 UTC, thomastaylor312 approved these changes
This is looking good now. I'd like @bacongobbler or @itowlson to review this before merge as well since it is going to break current users when they upgrade. Want to make sure we are ok with this

2020-10-02 16:42 UTC, thomastaylor312 commented on tests/integration_tests.rs
> +        .find(|t| (t.key == "kubernetes.io/arch") & (t.effect == "NoExecute"))
Any reason you are using bitwise and here over a boolean and?

2020-10-05 23:44 UTC, bacongobbler approved these changes
LGTM! Can you clarify what is the breaking change here though? Looks to me like we're just adding another taint to the nodes. Does that break existing pods if they upgraded Krustlet to 0.6? Trying to determine the severity/impact of the breaking change here. Thanks!

2020-10-06 00:03 UTC, kflansburg commented
Yep, as seen with our test cases after my first commit, any pod spec without the NoSchedule toleration will no longer schedule after this change. We should at least note in the release notes that people update their tolerations.

2020-10-06 17:03 UTC, merged