use --release
deislabs/krustlet pull request #440
Opened 2020-10-28 18:10 UTC by bacongobbler

Signed-off-by: Matthew Fisher <matt.fisher@microsoft.com>

2020-11-01 22:37 UTC, itowlson requested changes
Spotted one missed reference

2020-11-01 22:37 UTC, itowlson commented on docs/intro/tutorial01.md
>  We should now have the WebAssembly module created in `target/wasm32-wasi/debug`:
This also needs to be `release`.

2020-11-10 19:51 UTC, bacongobbler commented on docs/intro/tutorial01.md
>  We should now have the WebAssembly module created in `target/wasm32-wasi/debug`:
Good catch! Fixed.

2020-11-11 18:57 UTC, thomastaylor312 approved these changes

2020-11-11 19:22 UTC, itowlson approved these changes

2020-11-12 17:08 UTC, merged